### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [20]:
!pip install tensorflow-gpu

DEPRECATION: Loading egg at /Users/shivanshmahajan/anaconda3/lib/python3.11/site-packages/DiamondPricePrediction-0.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/shivanshmahajan/anaconda3/lib/python3.11/site-packages/Diamond_price_prediction-0.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/shivanshmahajan/anaconda3/lib/python3.11/site-packages/fonttools-4.46.0-py3.11-macosx-11.1-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
  Using cached tensorflow-

In [3]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[164, 253, 267, 305], [164, 253, 267, 31], [164, 484, 267, 332], [239, 485, 89, 218, 406], [239, 485, 89, 218, 256], [6, 164, 499, 267, 331], [178, 424, 58, 218]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 164 253 267 305]
 [  0   0   0   0 164 253 267  31]
 [  0   0   0   0 164 484 267 332]
 [  0   0   0 239 485  89 218 406]
 [  0   0   0 239 485  89 218 256]
 [  0   0   0   6 164 499 267 331]
 [  0   0   0   0 178 424  58 218]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/Users/shivanshmahajan/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 164, 253, 267, 305], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[-0.00421948,  0.01843804,  0.00053817, -0.03069173,  0.04850357,
         0.01439336,  0.0293702 , -0.04747602,  0.03268668,  0.00181542],
       [-0.00421948,  0.01843804,  0.00053817, -0.03069173,  0.04850357,
         0.01439336,  0.0293702 , -0.04747602,  0.03268668,  0.00181542],
       [-0.00421948,  0.01843804,  0.00053817, -0.03069173,  0.04850357,
         0.01439336,  0.0293702 , -0.04747602,  0.03268668,  0.00181542],
       [-0.00421948,  0.01843804,  0.00053817, -0.03069173,  0.04850357,
         0.01439336,  0.0293702 , -0.04747602,  0.03268668,  0.00181542],
       [ 0.04143481,  0.03076115,  0.00984691,  0.01720525, -0.00317071,
         0.01477909,  0.04383094,  0.0024844 , -0.0280838 , -0.04152268],
       [ 0.0254583 ,  0.01760336, -0.02885273,  0.04642751,  0.04425076,
         0.0154647 , -0.01872668,  0.01232039,  0.02717401,  0.04451041],
       [ 0.04521939,  0.0419029 , -0.01498396, -0.03755577,  0.02890951,
         0.02209527, -0.03361689,  0.03213361

In [17]:
print(model.predict(embedded_docs))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 164, 253, 267, 305], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]