In [3]:
import tensorflow as tf
print(tf.__version__)

2.13.0


# create tensor with tf.constant()

In [7]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
#CHECK THE NO OF DIMENSIONS IN TENSORFLOW

scalar.ndim

0

In [11]:
#create a vector

vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
vector.ndim

1

In [14]:
matrix=tf.constant([[10,10],[20,20],[30,30]])
matrix.ndim

2



tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

In [16]:
tensor.ndim

3

# creating tensor with tf.variable()

In [18]:
changeable_tensor=tf.Variable([10,10])
unchangeable_tensor=tf.constant([10,10])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [20]:
#how to assign changeable tensor
changeable_tensor[0].assign(3)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 3, 10], dtype=int32)>

# create random tensors

In [25]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

In [26]:
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffling Tensor

In [27]:
n_shuffle=tf.constant([[10,20],[20,30],[30,40]])
n_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30],
       [30, 40]], dtype=int32)>

In [28]:
tf.random.shuffle(n_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 30],
       [30, 40],
       [10, 20]], dtype=int32)>

In [29]:
tf.random.set_seed(42)#global level random seeds
tf.random.shuffle(n_shuffle,seed=42)#operationalm level rando0m seeds

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30],
       [30, 40]], dtype=int32)>

# others Ways

In [31]:
tf.ones([10,9])

<tf.Tensor: shape=(10, 9), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [32]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [34]:
import numpy as np
numpy_a=np.arange(1,25,dtype=np.int32)
numpy_a
#x=tf.constant(some_matrix)
#y=tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [38]:
A=tf.constant(numpy_a,shape=(2,3,4))
B=tf.constant(numpy_a)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [40]:
#Adding extra dimension by tf.newaxis



# Basic operation

In [42]:
tensor=tf.constant([[10,12],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 22],
       [13, 14]], dtype=int32)>

In [43]:
#original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 12],
       [ 3,  4]], dtype=int32)>

In [44]:
#tensor flow built in function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 120],
       [ 30,  40]], dtype=int32)>

# Matrix Multiplication
the inner dimension must match,
the resulting matrix has the shape of inner dimensions

In [45]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10 12]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[136, 168],
       [ 42,  52]], dtype=int32)>

In [46]:
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[136, 168],
       [ 42,  52]], dtype=int32)>

In [47]:
#create a tensor
x=tf.constant([[1,2],
               [3,4],
               [5,6]])
y=tf.constant([[4,2],
               [3,7],
               [1,3]])

In [48]:
x@tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18,  4,  9],
       [40, 10, 21],
       [62, 16, 33]], dtype=int32)>

In [49]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18,  4,  9],
       [40, 10, 21],
       [62, 16, 33]], dtype=int32)>

In [50]:
tf.matmul(tf.reshape(x,shape=(2,3)),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 25],
       [37, 61]], dtype=int32)>

In [51]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 38],
       [26, 50]], dtype=int32)>

In [53]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 38],
       [26, 50]], dtype=int32)>

tensordot:-tensor contraction of a and balong specified axesand outer product

# change the data type

In [55]:
b=tf.constant([1.7,1.4])
b.dtype

tf.float32

In [57]:
d=tf.cast(b,dtype=tf.float16)
d,d.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1.4], dtype=float16)>,
 tf.float16)